title: "Code for Germany"
description: "Stadt&lt;entwickler /&gt; nutzen offene Daten um ihre Stadt zu verbessern"
url: http://codefor.de
markdown: kramdown
exclude:
  - "vendor"
  - "CNAME"
  - "CONTRIBUTING.md"
  - "Gemfile*"
  - "mission"
  - "README.md"
  - "doc/"
  #- "projekte" # uncomment line to speed up jekyll build for development
  #- "blog" # uncomment line to speed up jekyll build for development
  #- "termine" # uncomment line to speed up jekyll build for development
  #- "presse" # uncomment line to speed up jekyll build for development
sass:
    style: :compressed
permalink: /blog/:title
excerpt_separator: "\n"
paginate: 5
paginate_path: "blog/:num"
gems:
  - jekyll-sitemap
collections:
  labs:
  termine:
  stories:
    output: true
    permalink: /stadtgeschichten/:path/
  stories_en:
    output: true
    permalink: /en/stadtgeschichten/:path/