title: "Code for Germany"
description: "Stadt&lt;entwickler /&gt;nutzen offene Daten um ihre Stadt zu verbessern"
url: http://codefor.de
markdown: kramdown
exclude: ["vendor"]
permalink: /blog/:title
excerpt_separator: "\n"
paginate: 5
paginate_path: "blog/:num"