title: "Code for Germany"
description: "Stadt&lt;entwickler /&gt; nutzen offene Daten um ihre Stadt zu verbessern"
url: http://codefor.de
markdown: kramdown
exclude:
  - "vendor"
  - "CNAME"
  - "Gemfile*"
  - "mission"
  - "README.md"
  - "doc/"
  - "update_avatars.py"
  #- "projekte" # uncomment line to speed up jekyll build for development
  #- "blog" # uncomment line to speed up jekyll build for development
  #- "presse" # uncomment line to speed up jekyll build for development
sass:
    style: :compressed
permalink: /blog/:title.html
excerpt_separator: "\n"
paginate: 5
paginate_path: "blog/:num"
gems:
  - jekyll-sitemap
  - jekyll-paginate
collections:
  labs:
  stories:
    output: true
    permalink: /stadtgeschichten/:path/
  stories_en:
    output: true
    permalink: /en/stadtgeschichten/:path/
  digitalrefugeelabs:
  wahlsalons:
    output: true
    permalink: /wahlsalons/:path/


